import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const onClick = () => {
    throw new Error("헤더바 에러");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <button onClick={onClick}>버튼</button>
    </>
  );
};

export default Home;
